### ISSUE TITLE
Utilize more information from exceptions

### ISSUE THREAD

**Issue by olejorgenb** [paperwm/gnome-shell-mode#1]
try {
        eval("let a = 1;\nerror_here,")
    } catch(e) {
        lasterr = e;
        [e.message, e.lineNumber,  e.columnNumber, e.fileName];
    }
    //: syntax error,166,11,resource:///org/gnome/shell/ui/shellDBus.js

Note the linenumber offset. Seems to be "line of eval in emacs.js + line in evaled code" or something. The columnNumber is correct.

Want a more stuctured return value from dbus Eval before working on this.

**Comment by hedning** [comment]
Should integrate with flycheck which should be pretty easy when we have the correct information:
```emacs-lisp
(flycheck-error-new &key BUFFER CHECKER FILENAME LINE COLUMN MESSAGE LEVEL ID
GROUP)
```
