### ISSUE TITLE
Evaluate code inside modules

### ISSUE THREAD

**Issue by olejorgenb** [paperwm/gnome-shell-mode#14]
An adhoc implementation is to add the project folder to `imports.searchPath` and wrap all eval calls like this:

    let module = imports.$FILENAME;
    with(module) {
       eval($CODE);
    }

Since all variables inside a module seems to be public and import doesn't reload the file, this seems to work ok.

To add new variables or redefine functions some extra work (or special code organization) is needed though. (I don't think there's a simply way to refer to the module object inside the module?)

**Comment by hedning** [comment]
This is fixed from a9b98af19f6fdd737b0aca51fb591b7846eefd7e and on-wards.
