### ISSUE TITLE
Don't override GnomeShell.prototype.Eval

### ISSUE THREAD

**Issue by olejorgenb** [paperwm/gnome-shell-mode#2]
We currently monkey-patch `imports.ui.shellDBus.GnomeShell.prototype.Eval`.

Before a proper release we should either make our own dbus service or adapt to the original Eval.

PS: See _handleMethodCall in Gio.js (gjs) for how the return value is marshalled.

**Comment by hedning** [comment]
fixed via: 4e07a52df1097fa69ab3fedac85a1ef651e542a0
